# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion-2017.2.2/bin/cmake/bin/cmake

# The command to remove a file.
RM = /opt/clion-2017.2.2/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/duc/Documents/homework/EE193/histogram

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/duc/Documents/homework/EE193/histogram

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/clion-2017.2.2/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/clion-2017.2.2/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/duc/Documents/homework/EE193/histogram/CMakeFiles /home/duc/Documents/homework/EE193/histogram/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/duc/Documents/homework/EE193/histogram/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named histogram

# Build rule for target.
histogram: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 histogram
.PHONY : histogram

# fast build rule for target.
histogram/fast:
	$(MAKE) -f CMakeFiles/histogram.dir/build.make CMakeFiles/histogram.dir/build
.PHONY : histogram/fast

ee193_utils.o: ee193_utils.cxx.o

.PHONY : ee193_utils.o

# target to build an object file
ee193_utils.cxx.o:
	$(MAKE) -f CMakeFiles/histogram.dir/build.make CMakeFiles/histogram.dir/ee193_utils.cxx.o
.PHONY : ee193_utils.cxx.o

ee193_utils.i: ee193_utils.cxx.i

.PHONY : ee193_utils.i

# target to preprocess a source file
ee193_utils.cxx.i:
	$(MAKE) -f CMakeFiles/histogram.dir/build.make CMakeFiles/histogram.dir/ee193_utils.cxx.i
.PHONY : ee193_utils.cxx.i

ee193_utils.s: ee193_utils.cxx.s

.PHONY : ee193_utils.s

# target to generate assembly for a file
ee193_utils.cxx.s:
	$(MAKE) -f CMakeFiles/histogram.dir/build.make CMakeFiles/histogram.dir/ee193_utils.cxx.s
.PHONY : ee193_utils.cxx.s

histogram.o: histogram.cxx.o

.PHONY : histogram.o

# target to build an object file
histogram.cxx.o:
	$(MAKE) -f CMakeFiles/histogram.dir/build.make CMakeFiles/histogram.dir/histogram.cxx.o
.PHONY : histogram.cxx.o

histogram.i: histogram.cxx.i

.PHONY : histogram.i

# target to preprocess a source file
histogram.cxx.i:
	$(MAKE) -f CMakeFiles/histogram.dir/build.make CMakeFiles/histogram.dir/histogram.cxx.i
.PHONY : histogram.cxx.i

histogram.s: histogram.cxx.s

.PHONY : histogram.s

# target to generate assembly for a file
histogram.cxx.s:
	$(MAKE) -f CMakeFiles/histogram.dir/build.make CMakeFiles/histogram.dir/histogram.cxx.s
.PHONY : histogram.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... histogram"
	@echo "... ee193_utils.o"
	@echo "... ee193_utils.i"
	@echo "... ee193_utils.s"
	@echo "... histogram.o"
	@echo "... histogram.i"
	@echo "... histogram.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

